baseurl: /wedding-template2/
url: https://project-agape.github.io

title: Wedding Template 2
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

markdown: kramdown

cover:
  name: "Bonnie & Clyde"

about:
  groom:
    groom-name: Clyde Ramos
    groom-image: 'groom.png'
    groom-description: "He is a great programmer who solves any problem through logic and reason. He also loves beer and a movie junkie as well. The founder of a Aestrea Software Development company, a startup and consulting company exclusively working for rocketmiles.com (a Priceline company)."

  bride:
    bride-name: Bonnie Dela Merced
    bride-image: 'bride.png'
    bride-description: "She is a codesigner (coder-designer), the Google Developer Group and Women Techmakers Community Lead for Cagayan de Oro. Josan's personal advocacy is inspiring women to become a techmaker. Currently, she plays around with her Gemma KIT, a Do-It-Yourslef wearable kit and travels to different places to share great things about it. She's also a UI/UX Engineer and co-founder of Aestrea Software Development."

outstory:
  - title: First time we met
    image: 'http://ndesaintheme.com/ulemulem/wp-content/uploads/2015/05/newyork.jpg'
    description: Cras varius, nunc et maximus ullamcorper, tellus tellus posuere ipsum, ac tincidunt orci tortor id sapien. Vivamus ultrices purus id nisl volutpat, et placerat nisi ultricies. Integer at vehicula elit. Ut non velit non dui finibus finibus. Duis feugiat ut est nec auctor. Nulla vestibulum, ante sit amet rutrum ornare, turpis nunc laoreet felis, quis pellentesque

  - title: First Date
    image: 'http://ndesaintheme.com/ulemulem/wp-content/uploads/2015/05/firstdate.jpg'
    description: Cras varius, nunc et maximus ullamcorper, tellus tellus posuere ipsum, ac tincidunt orci tortor id sapien. Vivamus ultrices purus id nisl volutpat, et placerat nisi ultricies. Integer at vehicula elit. Ut non velit non dui finibus finibus. Duis feugiat ut est nec auctor. Nulla vestibulum, ante sit amet rutrum ornare, turpis nunc laoreet felis, quis pellentesque

  - title: Engagement
    image: 'http://ndesaintheme.com/ulemulem/wp-content/uploads/2015/05/relationship.jpg'
    description: Cras varius, nunc et maximus ullamcorper, tellus tellus posuere ipsum, ac tincidunt orci tortor id sapien. Vivamus ultrices purus id nisl volutpat, et placerat nisi ultricies. Integer at vehicula elit. Ut non velit non dui finibus finibus. Duis feugiat ut est nec auctor. Nulla vestibulum, ante sit amet rutrum ornare, turpis nunc laoreet felis, quis pellentesque


wedding-details:
  venue:
    venue-day: "Sunday"
    venue-date: "May-22-2016"
    venue-time: "2:00 PM"
    venue-name: "Palazo Verde"
    venue-location: "Daang Reyna, Vista City, Las Pinas, Philippines"
  
  ceremony:
    ceremony-day: "Sunday"
    ceremony-date: "May-22-2016"
    ceremony-time: "2:00 PM"
    ceremony-name: "Palazo Verde"
    ceremony-location: "Daang Reyna, Vista City, Las Pinas, Philippines"


gallery:
  - image: 'gallery.jpg'
  - image: 'gallery.jpg'
  - image: 'gallery.jpg'
  - image: 'gallery.jpg'
  - image: 'gallery.jpg'
  - image: 'gallery.jpg'

    
